/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projet;

import static projet.BW.motDecompresser;
import static projet.Projet.decompression_mtf;

/**
 *
 * @author ma522501
 */
public class Interface extends javax.swing.JFrame {

    BW bw;
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setSize(800,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCentre = new javax.swing.JPanel();
        panelCompression = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaCompression = new javax.swing.JTextArea();
        labelCompression = new javax.swing.JLabel();
        panelDecompression = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelDecompression = new javax.swing.JLabel();
        panelNorth = new javax.swing.JPanel();
        zoneTexte = new javax.swing.JPanel();
        srollPane = new javax.swing.JScrollPane();
        chaineAcoder = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        zoneBouton = new javax.swing.JPanel();
        buttonBW = new javax.swing.JButton();
        buttonMTF = new javax.swing.JButton();
        buttonHuffman = new javax.swing.JButton();
        buttonAll = new javax.swing.JButton();
        panelSud = new javax.swing.JPanel();
        panelCodageFinal = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaCodeFinal = new javax.swing.JTextArea();
        labelCodeFinal = new javax.swing.JLabel();
        panelDecodageFinal = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        textAreaDecodageFinal = new javax.swing.JTextArea();
        labeDecodageFinal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCentre.setLayout(new java.awt.GridLayout(1, 2));

        panelCompression.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textAreaCompression.setColumns(20);
        textAreaCompression.setRows(5);
        textAreaCompression.setEnabled(false);
        jScrollPane1.setViewportView(textAreaCompression);

        panelCompression.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        labelCompression.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCompression.setText("Les étapes de la compression");
        panelCompression.add(labelCompression, java.awt.BorderLayout.PAGE_START);

        panelCentre.add(panelCompression);

        panelDecompression.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane2.setViewportView(jTextArea1);

        panelDecompression.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        labelDecompression.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDecompression.setText("Les étapes de la décompression");
        panelDecompression.add(labelDecompression, java.awt.BorderLayout.PAGE_START);

        panelCentre.add(panelDecompression);

        getContentPane().add(panelCentre, java.awt.BorderLayout.CENTER);

        panelNorth.setLayout(new java.awt.GridLayout(1, 2));

        zoneTexte.setLayout(new java.awt.BorderLayout());

        srollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chaineAcoder.setColumns(20);
        chaineAcoder.setRows(5);
        srollPane.setViewportView(chaineAcoder);

        zoneTexte.add(srollPane, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Votre texte : ");
        zoneTexte.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        panelNorth.add(zoneTexte);

        zoneBouton.setLayout(new java.awt.GridLayout(2, 2));

        buttonBW.setText("Burrows-Wheeler");
        buttonBW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBWActionPerformed(evt);
            }
        });
        zoneBouton.add(buttonBW);

        buttonMTF.setText("Move-to-front");
        zoneBouton.add(buttonMTF);

        buttonHuffman.setText("Huffman");
        zoneBouton.add(buttonHuffman);

        buttonAll.setText("All");
        zoneBouton.add(buttonAll);

        panelNorth.add(zoneBouton);

        getContentPane().add(panelNorth, java.awt.BorderLayout.NORTH);

        panelSud.setLayout(new java.awt.GridLayout(1, 2));

        panelCodageFinal.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textAreaCodeFinal.setColumns(20);
        textAreaCodeFinal.setRows(5);
        textAreaCodeFinal.setEnabled(false);
        jScrollPane3.setViewportView(textAreaCodeFinal);

        panelCodageFinal.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        labelCodeFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCodeFinal.setText("Code Final");
        panelCodageFinal.add(labelCodeFinal, java.awt.BorderLayout.PAGE_START);

        panelSud.add(panelCodageFinal);

        panelDecodageFinal.setLayout(new java.awt.BorderLayout());

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        textAreaDecodageFinal.setColumns(20);
        textAreaDecodageFinal.setRows(5);
        textAreaDecodageFinal.setEnabled(false);
        jScrollPane4.setViewportView(textAreaDecodageFinal);

        panelDecodageFinal.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        labeDecodageFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labeDecodageFinal.setText("Décodage Final");
        panelDecodageFinal.add(labeDecodageFinal, java.awt.BorderLayout.PAGE_START);

        panelSud.add(panelDecodageFinal);

        getContentPane().add(panelSud, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBWActionPerformed
        // TODO add your handling code here:
        String chaine = chaineAcoder.getText();
        if(!chaine.equals("") && !chaine.equals(null)){
            bw = new BW();
            bw.compression(chaine);
            String code = bw.code;
            textAreaCodeFinal.setText("Code final après Burrows Wheeler : " + code);
            
            bw.decompression(code);
            String decodage = bw.motDecompresser;
            textAreaDecodageFinal.setText("Décodafe après Burrows Wheeler : " + decodage);
            refreshListeBW();
        }
    }//GEN-LAST:event_buttonBWActionPerformed

    void refreshListeBW(){
        for(int i = 0 ; i < bw.liste.size() ; i++) bw.liste.remove(i);
        for(int i = 0 ; i < bw.listeDepart.size() ; i++) bw.listeDepart.remove(i);
        for(int i = 0 ; i < bw.listeTrier.size() ; i++) bw.listeTrier.remove(i);
        for(int i = 0 ; i < bw.listeCode.size() ; i++) bw.listeCode.remove(i);
        for(int i = 0 ; i < bw.listeClasse.size() ; i++) bw.listeClasse.remove(i);
        bw.mot="";
        bw.code="";
        bw.chiffre=0;
        motDecompresser="";
        bw.sauvegarde=-1;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAll;
    private javax.swing.JButton buttonBW;
    private javax.swing.JButton buttonHuffman;
    private javax.swing.JButton buttonMTF;
    private javax.swing.JTextArea chaineAcoder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labeDecodageFinal;
    private javax.swing.JLabel labelCodeFinal;
    private javax.swing.JLabel labelCompression;
    private javax.swing.JLabel labelDecompression;
    private javax.swing.JPanel panelCentre;
    private javax.swing.JPanel panelCodageFinal;
    private javax.swing.JPanel panelCompression;
    private javax.swing.JPanel panelDecodageFinal;
    private javax.swing.JPanel panelDecompression;
    private javax.swing.JPanel panelNorth;
    private javax.swing.JPanel panelSud;
    private javax.swing.JScrollPane srollPane;
    private javax.swing.JTextArea textAreaCodeFinal;
    private javax.swing.JTextArea textAreaCompression;
    private javax.swing.JTextArea textAreaDecodageFinal;
    private javax.swing.JPanel zoneBouton;
    private javax.swing.JPanel zoneTexte;
    // End of variables declaration//GEN-END:variables
}
